name: 🐛 Bug Report
description: Report a bug in EvoMap
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Clear description of what went wrong
      placeholder: "Describe the bug in detail..."
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of EvoMap is affected?
      multiple: false
      options:
        - Tree Visualization
        - Data Import/Export  
        - Tree Layout Algorithms
        - User Interface
        - Performance
        - Other
    validations:
      required: true
        
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Upload dataset '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: "Expected the tree to render correctly..."
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, the application crashed with error..."
    validations:
      required: true
      
  - type: textarea
    id: browser-info
    attributes:
      label: Browser & Environment
      description: Browser version, OS, device type
      placeholder: "Chrome 118, macOS 13.0, Desktop"
    validations:
      required: true
      
  - type: textarea
    id: dataset-info
    attributes:
      label: Dataset Information
      description: What phylogenetic data were you using?
      placeholder: "Tree format (Newick/phyloXML), number of species, data source..."
      
  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any error messages from browser console?
      placeholder: "Paste any console errors here..."
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Screenshots, logs, or other relevant information
      placeholder: "Add any other context about the problem here..."
