name: ✨ Feature Request
description: Suggest new functionality for EvoMap
labels: ["enhancement"]
body:
  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What type of feature are you requesting?
      multiple: false
      options:
        - New Visualization Type
        - Algorithm Implementation
        - Data Format Support
        - Accessibility Improvement
        - Performance Enhancement
        - Educational Feature
        - Export/Import Feature
        - User Interface Enhancement
        - Mobile/Touch Support
    validations:
      required: true
        
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Detailed description of the proposed feature
      placeholder: "Describe the feature you'd like to see..."
    validations:
      required: true
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be used? What problem does it solve?
      placeholder: "As a researcher/educator/student, I want to..."
    validations:
      required: true
      
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: "I think this could be implemented by..."
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: "Alternative approaches could include..."
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      multiple: false
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my work
        - Critical - Blocking my research
        
  - type: checkboxes
    id: implementation-help
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I can help with research and design
        - label: I can help with coding/implementation
        - label: I can help with testing
        - label: I can help with documentation
        
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Screenshots, mockups, references, or other relevant information
      placeholder: "Add any other context, screenshots, or examples here..."
